// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RMXBsvzLB6-GfV0dG8h-6293m1Dgoao',
    appId: '1:618249651056:web:5cd9c51881a6874a80c5b5',
    messagingSenderId: '618249651056',
    projectId: 'pokemon-marketplace-project',
    authDomain: 'pokemon-marketplace-project.firebaseapp.com',
    storageBucket: 'pokemon-marketplace-project.firebasestorage.app',
    measurementId: 'G-9MTK85N4VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB94om-5b4Y-Zx_9RL9ANJ4eOP3c7x78Pk',
    appId: '1:618249651056:android:f6e43e806a6d249a80c5b5',
    messagingSenderId: '618249651056',
    projectId: 'pokemon-marketplace-project',
    storageBucket: 'pokemon-marketplace-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeD0UAzLtH7RuelEI9u_KwdsC-phkH5Jo',
    appId: '1:618249651056:ios:3ea4fd9797d9460e80c5b5',
    messagingSenderId: '618249651056',
    projectId: 'pokemon-marketplace-project',
    storageBucket: 'pokemon-marketplace-project.firebasestorage.app',
    iosBundleId: 'com.example.pokemonWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeD0UAzLtH7RuelEI9u_KwdsC-phkH5Jo',
    appId: '1:618249651056:ios:3ea4fd9797d9460e80c5b5',
    messagingSenderId: '618249651056',
    projectId: 'pokemon-marketplace-project',
    storageBucket: 'pokemon-marketplace-project.firebasestorage.app',
    iosBundleId: 'com.example.pokemonWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6RMXBsvzLB6-GfV0dG8h-6293m1Dgoao',
    appId: '1:618249651056:web:ae80716dd110a5d180c5b5',
    messagingSenderId: '618249651056',
    projectId: 'pokemon-marketplace-project',
    authDomain: 'pokemon-marketplace-project.firebaseapp.com',
    storageBucket: 'pokemon-marketplace-project.firebasestorage.app',
    measurementId: 'G-F0X4S6MZP9',
  );
}
