// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// KODE YANG BERFUNGSI SEBAGAI PENGHUBUNG
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgs8F4fPaxWvEzeu-3lKfXo1dv3EyglUU',
    appId: '1:916574992698:web:822b1c58ccf00b11fcf803',
    messagingSenderId: '916574992698',
    projectId: 'pokemon-marketplace-reza',
    authDomain: 'pokemon-marketplace-reza.firebaseapp.com',
    storageBucket: 'pokemon-marketplace-reza.firebasestorage.app',
    measurementId: 'G-PMYSX5VE83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnrNMO1GRc7JPmaqwo8B4uU_xht3nvcRA',
    appId: '1:916574992698:android:8f8d274f1be1856ffcf803',
    messagingSenderId: '916574992698',
    projectId: 'pokemon-marketplace-reza',
    storageBucket: 'pokemon-marketplace-reza.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHzB7phSB2Vut4bU9vUdm8dg0tJPdiEOc',
    appId: '1:916574992698:ios:bca7b3f0019287c0fcf803',
    messagingSenderId: '916574992698',
    projectId: 'pokemon-marketplace-reza',
    storageBucket: 'pokemon-marketplace-reza.firebasestorage.app',
    iosBundleId: 'com.example.pokemonWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHzB7phSB2Vut4bU9vUdm8dg0tJPdiEOc',
    appId: '1:916574992698:ios:bca7b3f0019287c0fcf803',
    messagingSenderId: '916574992698',
    projectId: 'pokemon-marketplace-reza',
    storageBucket: 'pokemon-marketplace-reza.firebasestorage.app',
    iosBundleId: 'com.example.pokemonWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgs8F4fPaxWvEzeu-3lKfXo1dv3EyglUU',
    appId: '1:916574992698:web:9ef9fff2c45f939ffcf803',
    messagingSenderId: '916574992698',
    projectId: 'pokemon-marketplace-reza',
    authDomain: 'pokemon-marketplace-reza.firebaseapp.com',
    storageBucket: 'pokemon-marketplace-reza.firebasestorage.app',
    measurementId: 'G-KG7WN8FE7D',
  );
}
